# Starter pipeline
name: $(BuildDefinitionName)_$(date:yyyyMMdd)$(rev:.r)

trigger:
- main

pool: local

variables:
  - name: name
    value: 'tamops'

stages :
  - stage: terraform
    jobs:
    - job: tf_run
      continueOnError: false
      steps:
      - task: charleszipp.azure-pipelines-tasks-terraform.azure-pipelines-tasks-terraform-installer.TerraformInstaller@0
        displayName: install terraform
        inputs:
          terraformVersion: latest
      - task: TerraformCLI@0
        displayName: 'check terraform version'
        inputs:
          command: version
      - task: TerraformCLI@0
        displayName: 'terraform init'
        inputs:
          command: 'init'
          workingDirectory: '$(System.DefaultWorkingDirectory)'
          backendType: 'aws'
          allowTelemetryCollection: true
          backendServiceAws: 'aws-jenkins-new'
          backendAwsRegion: 'us-east-2'
          backendAwsBucket: 'bipro-s3bucket'
          backendAwsKey: 'tf-backend/'
      - task: TerraformCLI@0
        displayName: 'terraform validate'
        inputs:
          command: 'validate'
          workingDirectory: '$(System.DefaultWorkingDirectory)'
          allowTelemetryCollection: true
      - task: TerraformCLI@0
        displayName: 'terraform plan'
        inputs:
          command: 'plan'
          workingDirectory: '$(System.DefaultWorkingDirectory)'
          allowTelemetryCollection: true
          providerServiceAws: 'aws-jenkins-new'
          providerAwsRegion: 'us-east-1'
      - task: TerraformCLI@0
        displayName: 'terraform apply'
        inputs:
          command: 'apply'
          workingDirectory: '$(System.DefaultWorkingDirectory)'
          allowTelemetryCollection: true
          providerServiceAws: 'aws-jenkins-new'
          providerAwsRegion: 'us-east-1'

